server.name: kibana
server.host: "0.0.0.0"

# Elasticsearch connection
elasticsearch.hosts: ["http://elasticsearch:9200"]

# Security settings for local development
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "fhjskadhflak3q74618fhjskadhflak3q74618"  # 32+ chars
xpack.reporting.encryptionKey: "lkajhf98q34ltkja9814lkajhf98q34ltkja9814"           # 32+ chars
xpack.security.encryptionKey: "alksjdhf9q834kljash891alksjdhf9q834kljash891"         # 32+ chars

# SSL settings
server.ssl.enabled: false
elasticsearch.ssl.verificationMode: none

# CSP settings
# server.csp.rules:
#   - "default-src 'self' 'unsafe-eval' 'unsafe-inline'"
#   - "img-src 'self' 'unsafe-inline' data: blob:"
#   - "style-src 'self' 'unsafe-inline'"
#   - "font-src 'self'"
#   - "connect-src 'self' http: https:"
csp.strict: false